# Generated by Django 4.0 on 2022-02-21 16:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_blog_news_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 21, 16, 39, 24, 796274, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 21, 16, 39, 32, 726589, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 21, 16, 39, 34, 756612, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
