# Generated by Django 4.0 on 2022-02-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_blog_ctime_comments_ctime_news_ctime'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
