# Generated by Django 3.2.12 on 2022-05-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_news_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='images',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='images',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
