# Generated by Django 3.2.12 on 2022-05-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_auto_20220528_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='userpic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='userpics'),
        ),
    ]
