# Generated by Django 3.2.12 on 2022-05-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_auto_20220528_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='firstname',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='surname',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
